### ISSUE TITLE
ToInt method implementation

### ISSUE THREAD

**Issue by GintasS** [ardalis/Ardalis.Extensions#5]
Hello.

I saw a  `ToInt()` method in StringExtensions and it has raised me a question:
- Why int.Parse() is being used instead of int.TryParse()? This way, if a string is not a valid number, we wouldn't get an exception.
- Also, I think we should handle the cases where a string is a number that is out of bounds (int.MaxValue and int.MinValue) and throw exceptions or something else.

**Comment by ShadyNagy** [comment]
@GintasS 
Yes, sure int.TryParse() is better than int.parse() then no need also for your 2nd check.

**Comment by ardalis** [comment]
Sometimes an exception is what you want.
If the value is out of range of an int, an exception will be thrown by int.Parse already.

To my mind there are a few considerations here:

- Is a non-numeric value (or out of range) an exceptional circumstance?
- If not, what should be returned?
  - Zero?
  - null?
  - False?

If we return int and the use case is simple. If it works, you get an int. If it doesn't, you get an exception.

If we don't throw, then we have more decisions to make.
If it works, you get an int.
If it's empty or null, you get 0. (Should you, though?)
If it doesn't work, you get null (or false; or zero).

You might end up having to return a `Maybe<int>` or a `Result<int>` or at least an `int?` in the non-exception case.

Personally, I rarely use TryParse and if I call int.Parse it's because I'm confident the string should be an int. If it's not, that's exceptional. But I'm open to supporting other use cases, either on the same extension or more likely on a separate one.

Example:

```
int result = "123".ToInt();
int? result2 = "234.34".ToMaybeInt(); // returns null if it cannot parse to int
```

```

**Comment by ShadyNagy** [comment]
@ardalis 
ToMaybeInt added on PR #7

**Comment by GintasS** [comment]
> Sometimes an exception is what you want.
> If the value is out of range of an int, an exception will be thrown by int.Parse already.
> 
> To my mind there are a few considerations here:
> 
> * Is a non-numeric value (or out of range) an exceptional circumstance?
> * If not, what should be returned?
>   
>   * Zero?
>   * null?
>   * False?
> 
> If we return int and the use case is simple. If it works, you get an int. If it doesn't, you get an exception.
> 
> If we don't throw, then we have more decisions to make.
> If it works, you get an int.
> If it's empty or null, you get 0. (Should you, though?)
> If it doesn't work, you get null (or false; or zero).
> 
> You might end up having to return a `Maybe<int>` or a `Result<int>` or at least an `int?` in the non-exception case.
> 
> Personally, I rarely use TryParse and if I call int.Parse it's because I'm confident the string should be an int. If it's not, that's exceptional. But I'm open to supporting other use cases, either on the same extension or more likely on a separate one.
> 
> Example:
> 
> ```
> int result = "123".ToInt();
> int? result2 = "234.34".ToMaybeInt(); // returns null if it cannot parse to int
> ```

Your remarks are to the point! But I was writing this in regards of having explicit exceptions, and having all the validation/ exception logic in the extension method itself, with the help of the XML comment that would explain all possible exceptions. 

But I guess int.Parse is also a valid choice.
